import unittest

from helpers import line_rules, scanner, text_rules

from no_ai_marks.git import Commit

ROBOT = "\U0001F916"


class TrailerTest(unittest.TestCase):
    def test_claude_co_author(self):
        self.assertEqual(text_rules("Fix it\n\nCo-Authored-By: Claude <noreply@anthropic.com>"), ["ai-trailer"])

    def test_model_name_in_trailer(self):
        self.assertEqual(text_rules("Co-authored-by: Claude Opus 4.5 <x@example.com>"), ["ai-trailer"])

    def test_kernel_style_assisted_by(self):
        self.assertEqual(text_rules("Assisted-by: Claude:claude-3-opus"), ["ai-trailer"])

    def test_copilot_agent_email(self):
        self.assertEqual(
            text_rules("Co-authored-by: someone <198982749+Copilot@users.noreply.github.com>"),
            ["ai-trailer"],
        )

    def test_ai_prefixed_trailer(self):
        self.assertEqual(text_rules("AI-Assisted: yes"), ["ai-trailer"])
        self.assertEqual(text_rules("AI-Assisted: no"), [])

    def test_humans_named_claude_pass(self):
        self.assertEqual(text_rules("Co-authored-by: Claude Shannon <claude@bell-labs.example>"), [])
        self.assertEqual(text_rules("Co-authored-by: Claude-Henri Dupont <chd@example.com>"), [])
        self.assertEqual(text_rules("Reviewed-by: Devin Smith <devin@example.com>"), [])

    def test_ordinary_trailers_pass(self):
        self.assertEqual(text_rules("Signed-off-by: Jane Dev <jane@example.com>\nFixes: #12"), [])


class FooterTest(unittest.TestCase):
    def test_claude_code_footer(self):
        rules = text_rules(f"{ROBOT} Generated with [Claude Code](https://claude.com/claude-code)")
        self.assertEqual(sorted(rules), ["ai-emoji", "ai-footer"])

    def test_pr_statement(self):
        self.assertEqual(text_rules("This PR was generated by Codex."), ["ai-footer"])

    def test_policy_text_passes(self):
        self.assertEqual(text_rules("Code generated by AI tools is not accepted."), [])
        self.assertEqual(text_rules("Do not submit code generated by AI."), [])

    def test_file_headers(self):
        self.assertEqual(line_rules(";;; Generated with ChatGPT", "src/util.lisp"), ["ai-footer"])
        self.assertEqual(line_rules("# Code generated by AI. DO NOT EDIT."), ["ai-footer"])
        self.assertEqual(line_rules("<!-- Written with the help of Claude -->", "docs/a.md"), ["ai-footer"])
        self.assertEqual(line_rules('  "author": "ChatGPT",', "package.json"), ["ai-footer"])
        self.assertEqual(line_rules('<meta name="generator" content="ChatGPT">', "index.html"), ["ai-footer"])

    def test_ordinary_generated_headers_pass(self):
        self.assertEqual(line_rules("// Code generated by protoc-gen-go. DO NOT EDIT."), [])
        self.assertEqual(line_rules("# Generated by Django 5.1 on 2026-01-01"), [])
        self.assertEqual(line_rules("// Written by Claude Dupont, 1998"), [])

    def test_allow_marker(self):
        self.assertEqual(line_rules("Generated with Claude Code  <!-- no-ai-marks: allow -->"), [])


class TagAndLinkTest(unittest.TestCase):
    def test_tags(self):
        self.assertEqual(text_rules("[AI] Refactor parser"), ["ai-tag"])
        self.assertEqual(text_rules("Refactor parser (via Claude)"), ["ai-tag"])
        self.assertEqual(text_rules("Refactor parser (generated with Copilot)"), ["ai-tag"])

    def test_tag_lookalikes_pass(self):
        self.assertEqual(text_rules("Route requests via Claude API when enabled"), [])
        self.assertEqual(text_rules("Add AI-generated alt text feature"), [])

    def test_session_links(self):
        self.assertEqual(text_rules("See https://chatgpt.com/share/abc123"), ["ai-session-link"])
        self.assertEqual(line_rules("<!-- https://claude.ai/code/session_01abc -->"), ["ai-session-link"])

    def test_bot_email_in_file(self):
        self.assertEqual(line_rules(";; Maintainer: Bot <noreply@anthropic.com>"), ["ai-identity"])


class IdentityAndBranchTest(unittest.TestCase):
    def commit_rules(self, author, email):
        s = scanner()
        s.commit(Commit("a" * 40, author, email, "Jane Dev", "jane@example.com", "Fix\n"))
        return [f.rule for f in s.findings]

    def test_ai_authors(self):
        self.assertEqual(self.commit_rules("Copilot", "198982749+Copilot@users.noreply.github.com"), ["ai-identity"])
        self.assertEqual(self.commit_rules("Jane Dev (aider)", "jane@example.com"), ["ai-identity"])
        self.assertEqual(self.commit_rules("Cursor Agent", "cursoragent@cursor.com"), ["ai-identity"])
        self.assertEqual(self.commit_rules("devin-ai-integration[bot]", "x@example.com"), ["ai-identity"])

    def test_human_authors(self):
        self.assertEqual(self.commit_rules("Claude Shannon", "claude@example.com"), [])
        self.assertEqual(self.commit_rules("Devin", "devin@example.com"), [])

    def branch_rules(self, name):
        s = scanner()
        s.branch(name)
        return [f.rule for f in s.findings]

    def test_branches(self):
        self.assertEqual(self.branch_rules("claude/fix-login"), ["ai-branch"])
        self.assertEqual(self.branch_rules("Copilot/fix-123"), ["ai-branch"])
        self.assertEqual(self.branch_rules("feature/claude-integration"), [])
        self.assertEqual(self.branch_rules("main"), [])


if __name__ == "__main__":
    unittest.main()
