"""Wording around tool names: attribution phrases, tags, and trailers.

Tool names come from the registry (registry.py and data/tools.toml). This
module holds only the grammar around them, which rarely changes.
"""

from __future__ import annotations

import functools
import re
from dataclasses import dataclass

ROBOT = "\U0001F916"

_VERBS = r"""(?:generated | written | created | authored | co-?authored | co-?written
  | produced | drafted | composed | made | coded | assisted | suggested
  | pair[-\s]programmed | vibe[-\s]coded)"""
_PREPS = r"(?:with|by|using|via|through)"
_HELP = r"(?:(?:the\s+)?(?:help|assistance|support)\s+(?:of|from)\s+)?"
_DECOR = r"""[\[(`*_"'\s]*"""

# "Code generated by AI tools is not accepted" is policy, not attribution.
_NOT_POLICY = r"""(?!\s+(?:tools?|models?|assistants?|agents?|is|are|was|were|must|should
  | may|might|will|won't|can|cannot|can't|isn't|aren't|not|usage|use|policy)\b)"""

_SUBJECT = r"""(?:
    (?:(?:portions|parts|some|much|most|all)\s+of\s+)?
    (?:this\s+|the\s+|an?\s+)?
    (?:(?:automatic|automated)\s+)?
    (?:code|file|module|script|content|text|documentation|document|docs?|page|tests?
      |image|video|diagram|translation|comments?|readme|function|class|implementation
      |pr|pull\s+request|commit|changes?|patch|fix(?:es)?|description|summary|message)
    \s+(?:(?:was|is|were|are|has\s+been|have\s+been)\s+)?
)?"""
_ADVERB_WORDS = r"""(?:partially|partly|fully|mostly|entirely|largely|completely
  | primarily|automatically|originally|initially)"""
_ADVERB = rf"(?:{_ADVERB_WORDS}\s+)?"
_ADVERB_AFTER = rf"(?:\s+{_ADVERB_WORDS})?"
# "Docs: Generated with ...", "Note: written by ..."
_LABEL = r"(?:[A-Za-z][\w-]*:\s+)?"

# IPTC digital source type for AI-generated media, as it appears in XMP or SVG.
TEXT_PROVENANCE = re.compile(r"(?:composite)?(?:with)?trainedAlgorithmicMedia", re.I)

# Trailers: "Key: value" lines. PR bodies sometimes bullet or quote them.
TRAILER = re.compile(r"^[\s>*-]*([A-Za-z][A-Za-z0-9-]*)[ \t]*:[ \t]*(\S.*)$")
AI_TRAILER_KEY = re.compile(r"(?:x-)?(?:ai|llm|genai)(?:-[a-z-]*)?", re.I)
CREDIT_KEY = re.compile(r".+-(?:by|with)", re.I)
NEGATIVE_VALUES = frozenset({"no", "none", "false", "n/a", "na", "0", "-"})


@dataclass(frozen=True)
class Patterns:
    attribution: re.Pattern
    author_field: re.Pattern
    generator_field: re.Pattern
    ai_tag: re.Pattern


@functools.lru_cache(maxsize=None)
def build(registry) -> Patterns:
    """Compile the phrases around the registry's tool names."""
    # The grammar is verbose (x) mode; names and user patterns are not.
    names = f"(?-x:{registry.phrase_names})"
    tags = f"(?-x:{registry.tag_names})"
    return Patterns(
        # At the start of a line, after any comment or list markers:
        # "Generated with [Claude Code](...)", ";;; Written by ChatGPT".
        attribution=re.compile(
            rf"""^[\W_]*{_LABEL}(?P<core>{_SUBJECT}{_ADVERB}{_VERBS}{_ADVERB_AFTER}[\s:-]+{_PREPS}[\s:]+{_HELP}{_DECOR}
            (?P<name>{names})(?!\w){_NOT_POLICY})""",
            re.I | re.X,
        ),
        # "Author: ChatGPT", "@author Claude", '"author": "Copilot"'
        author_field=re.compile(
            rf"""^[\W_]*(?P<core>@?(?:author|authors|maintainer|written[-\s]by|created[-\s]by)["']?
            \s*[:=]?\s*{_DECOR}(?P<name>{names})(?!\w){_NOT_POLICY})""",
            re.I | re.X,
        ),
        # <meta name="generator" content="ChatGPT">, generator: Claude
        generator_field=re.compile(
            rf"""\bgenerator["']?\s*(?:[:=]|content\s*=)\s*["']?[^"'\n>]{{0,40}}?
            (?<!\w)(?P<name>{names})(?!\w)""",
            re.I | re.X,
        ),
        # [AI], (AI-generated), (via Claude), "- by Copilot" at the end of a line
        ai_tag=re.compile(
            rf"""
            [\[(]\s*(?:ai|llm|gpt|genai)(?:[\s-]+(?:generated|assisted|authored|written|created))?\s*[\])]
          | ^\W*(?:ai|llm|genai)[\s-]+(?:generated|assisted)\W*$
          | [\[(]\s*(?:via|by|with|using|from)\s+{tags}\s*[\])]
          | [\[(]\s*{_VERBS}[\s:-]+{_PREPS}\s+{names}(?!\w)[^\])]*[\])]
          | (?:^|[-\U00002013\U00002014|]\s*)(?:via|by|with)\s+{tags}\W*$
            """,
            re.I | re.X,
        ),
    )
